### ISSUE TITLE
Renaming and setting an enter or leave message does not work on 1.19.1

### ISSUE THREAD

**Issue by insertapp** [WhipDevelopment/CrashClaim#20]
Hello, we have just started using crash claims on the server, it was working fine on 1.19 but 1.19.1 doesn't work properly due to the following error:
```
21.08 20:58:50 [Server] ERROR Could not pass event InventoryClickEvent to CrashClaim v1.0.33
21.08 20:58:50 [Server] INFO java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.PlayerInventory net.minecraft.server.level.EntityPlayer.fB()'
21.08 20:58:50 [Server] INFO at net.wesjd.anvilgui.version.Wrapper1_19_R1$AnvilContainer.<init>(Wrapper1_19_R1.java:88) ~[CrashClaim.jar:?]
21.08 20:58:50 [Server] INFO at net.wesjd.anvilgui.version.Wrapper1_19_R1.newContainerAnvil(Wrapper1_19_R1.java:82) ~[CrashClaim.jar:?]
21.08 20:58:50 [Server] INFO at net.wesjd.anvilgui.AnvilGUI.openInventory(AnvilGUI.java:177) ~[CrashClaim.jar:?]
21.08 20:58:50 [Server] INFO at net.wesjd.anvilgui.AnvilGUI.<init>(AnvilGUI.java:165) ~[CrashClaim.jar:?]
21.08 20:58:50 [Server] INFO at net.wesjd.anvilgui.AnvilGUI.<init>(AnvilGUI.java:30) ~[CrashClaim.jar:?]
21.08 20:58:50 [Server] INFO at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[CrashClaim.jar:?]
21.08 20:58:50 [Server] INFO at net.crashcraft.crashclaim.menus.ClaimMenu.onClick(ClaimMenu.java:168) ~[CrashClaim.jar:?]
21.08 20:58:50 [Server] INFO at net.crashcraft.crashclaim.crashutils.menusystem.CrashMenuController.onInventoryClickEvent(CrashMenuController.java:44) ~[CrashClaim.jar:?]
21.08 20:58:50 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor593.execute(Unknown Source) ~[?:?]
21.08 20:58:50 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
21.08 20:58:50 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:git-Purpur-1746]
21.08 20:58:50 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
21.08 20:58:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
21.08 20:58:50 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3369) ~[?:?]
21.08 20:58:50 [Server] INFO at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
21.08 20:58:50 [Server] INFO at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
21.08 20:58:50 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
21.08 20:58:50 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.1.jar:git-Purpur-1746]
21.08 20:58:50 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
21.08 20:58:50 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
21.08 20:58:50 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1386) ~[purpur-1.19.1.jar:git-Purpur-1746]
21.08 20:58:50 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.1.jar:git-Purpur-1746]
21.08 20:58:50 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
21.08 20:58:50 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1363) ~[purpur-1.19.1.jar:git-Purpur-1746]
21.08 20:58:50 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1356) ~[purpur-1.19.1.jar:git-Purpur-1746]
21.08 20:58:50 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
21.08 20:58:50 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1334) ~[purpur-1.19.1.jar:git-Purpur-1746]
21.08 20:58:50 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[purpur-1.19.1.jar:git-Purpur-1746]
21.08 20:58:50 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.1.jar:git-Purpur-1746]
```
The server version is 
```
21.08 21:03:47 [Server] INFO Current: git-Purpur-1746 (MC: 1.19.1)*
21.08 21:03:47 [Server] INFO Previous: git-Purpur-1735 (MC: 1.19)
21.08 21:03:47 [Server] INFO * You are 5 version(s) behind
```
hopefully this helps!

**Comment by Log1x** [comment]
I already did a PR for this. If you want to hop in the CrashClaim Discord I can give you a jar.

**Comment by insertapp** [comment]
alr I have joined, I’m inset username here

**Comment by insertapp** [comment]
This issue was fixed a long time ago, guess this wasn't closed
